---
# The following configuration sets the following
# The hostname and updates the hosts file
- name: Set the hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
- name: Update /etc/hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.1.1 {{ hostname }}"
    state: present
